apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: poc-teste
spec:
  replicas: 1 # Executa 1 cópia para alta disponibilidade
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/wanderms25/pda_nbr5419_backend:1.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: pda-config
            - secretRef:
                name: pda-secrets
          # Opcional: Define a URL completa do banco montando as variáveis
          env:
            - name: DATABASE_URL
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: backend-service
#   namespace: poc-teste
# spec:
#   selector:
#     app: backend
#   ports:
#     - protocol: TCP
#       port: 8000
#       targetPort: 8000